/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-hpsdr
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_HPSDR_API_H
#define INCLUDED_HPSDR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_hpsdr_EXPORTS
#define HPSDR_API __GR_ATTR_EXPORT
#else
#define HPSDR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_HPSDR_API_H */
