/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(hermesWB.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(86712d3673b8c4face55c0f30412e24e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hpsdr/hermesWB.h>
// pydoc.h is automatically generated in the build directory
#include <hermesWB_pydoc.h>

void bind_hermesWB(py::module& m)
{

    using hermesWB    = ::gr::hpsdr::hermesWB;


    py::class_<hermesWB, gr::block, gr::basic_block,
        std::shared_ptr<hermesWB>>(m, "hermesWB", D(hermesWB))

        .def(py::init(&hermesWB::make),
           py::arg("RxPre"),
           py::arg("Intfc"),
           py::arg("ClkS"),
           py::arg("AlexRA"),
           py::arg("AlexTA"),
           py::arg("AlexHPF"),
           py::arg("AlexLPF"),
           py::arg("MACAddr"),
           D(hermesWB,make)
        )
        




        
        .def("set_RxPreamp",&hermesWB::set_RxPreamp,       
            py::arg("arg0"),
            D(hermesWB,set_RxPreamp)
        )


        
        .def("set_ClockSource",&hermesWB::set_ClockSource,       
            py::arg("arg0"),
            D(hermesWB,set_ClockSource)
        )


        
        .def("set_AlexRxAntenna",&hermesWB::set_AlexRxAntenna,       
            py::arg("arg0"),
            D(hermesWB,set_AlexRxAntenna)
        )


        
        .def("set_AlexTxAntenna",&hermesWB::set_AlexTxAntenna,       
            py::arg("arg0"),
            D(hermesWB,set_AlexTxAntenna)
        )


        
        .def("set_AlexRxHPF",&hermesWB::set_AlexRxHPF,       
            py::arg("arg0"),
            D(hermesWB,set_AlexRxHPF)
        )


        
        .def("set_AlexTxLPF",&hermesWB::set_AlexTxLPF,       
            py::arg("arg0"),
            D(hermesWB,set_AlexTxLPF)
        )


        
        .def("stop",&hermesWB::stop,       
            D(hermesWB,stop)
        )


        
        .def("start",&hermesWB::start,       
            D(hermesWB,start)
        )

        ;




}








